package com.olakai.app

import com.olakai.app.data.catalog.LandOutline
import com.olakai.app.data.model.AirportIndex
import com.olakai.app.data.model.SpotCatalog
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * The bundled assets are hand-maintained and regenerated by scripts, so the
 * likeliest way to crash this app on launch is a JSON file that no longer
 * matches its model. Parse the real files with the real serializers here, where
 * it costs a second, rather than finding out on a phone.
 */
class AssetParsingTest {

    private val json = Json {
        ignoreUnknownKeys = true
        isLenient = true
        explicitNulls = false
        coerceInputValues = true
    }

    private fun asset(name: String): String {
        val file = File("src/main/assets/$name")
        assertTrue("missing asset: ${file.absolutePath}", file.exists())
        return file.readText()
    }

    @Test
    fun `spot catalog parses and every spot is usable`() {
        val catalog = json.decodeFromString<SpotCatalog>(asset("spots.json"))
        assertTrue("catalog is empty", catalog.spots.size >= 50)

        val ids = mutableSetOf<String>()
        catalog.spots.forEach { spot ->
            assertTrue("duplicate spot id ${spot.id}", ids.add(spot.id))
            assertTrue("${spot.id}: blank name", spot.name.isNotBlank())
            assertTrue("${spot.id}: latitude out of range", spot.lat in -90.0..90.0)
            assertTrue("${spot.id}: longitude out of range", spot.lon in -180.0..180.0)
            assertTrue("${spot.id}: no airport", spot.access.airports.isNotEmpty())
            assertTrue("${spot.id}: empty write-up", spot.info.about.length > 80)
            assertTrue("${spot.id}: no external cam fallback", spot.externalCams.isNotEmpty())
        }
    }

    @Test
    fun `every spot names airports that exist in the index`() {
        val catalog = json.decodeFromString<SpotCatalog>(asset("spots.json"))
        val codes = json.decodeFromString<AirportIndex>(asset("airports.json"))
            .airports.map { it.iata }.toSet()

        catalog.spots.forEach { spot ->
            spot.access.airports.forEach { iata ->
                assertTrue("${spot.id} points at unknown airport $iata", iata in codes)
            }
        }
    }

    @Test
    fun `airport index parses with sane coordinates`() {
        val index = json.decodeFromString<AirportIndex>(asset("airports.json"))
        assertTrue("suspiciously small airport index", index.airports.size > 1000)
        index.airports.take(500).forEach { airport ->
            assertEquals("bad IATA ${airport.iata}", 3, airport.iata.length)
            assertTrue(airport.lat in -90.0..90.0)
            assertTrue(airport.lon in -180.0..180.0)
        }
    }

    @Test
    fun `cam catalog parses and only references spots that exist`() {
        val catalog = json.decodeFromString<SpotCatalog>(asset("spots.json"))
        val spotIds = catalog.spots.map { it.id }.toSet()
        val cams = json.decodeFromString<Map<String, List<ResolvedCam>>>(asset("cams.json"))

        assertTrue("no cams bundled", cams.values.sumOf { it.size } > 0)
        cams.forEach { (spotId, list) ->
            assertTrue("cams.json references unknown spot $spotId", spotId in spotIds)
            list.forEach { cam ->
                assertTrue(
                    "$spotId: cam has neither channel nor video id",
                    cam.channelId.isNotBlank() || cam.videoId.isNotBlank(),
                )
                if (cam.channelId.isNotBlank()) {
                    assertTrue(
                        "$spotId: '${cam.channelId}' is not a YouTube channel id",
                        cam.channelId.startsWith("UC") && cam.channelId.length == 24,
                    )
                }
            }
        }
    }

    @Test
    fun `coastline outline parses into drawable rings`() {
        val land = json.decodeFromString<LandOutline>(asset("world_land.json"))
        assertTrue("no coastlines", land.polygons.isNotEmpty())
        land.polygons.forEach { ring ->
            assertTrue("degenerate ring", ring.size >= 4)
            ring.forEach { point ->
                assertEquals(2, point.size)
                assertTrue(point[0] in -180.0..180.0)
                assertTrue(point[1] in -90.0..90.0)
            }
        }
    }

    @kotlinx.serialization.Serializable
    private data class ResolvedCam(
        val videoId: String = "",
        val channelId: String = "",
        val title: String = "",
        val channel: String = "",
        val channelUrl: String = "",
    )
}
