#!/usr/bin/env python3
"""Generate the OlaKai wave mark.

The mark is a logarithmic spiral: a curling wave genuinely is one, so the curl
tightens the way water does instead of the way a hand-drawn bezier guesses. The
spiral is generated here and emitted twice -- as an SVG for review, and as the
Android adaptive-icon vector drawables -- so the launcher icon is always exactly
the artwork that was reviewed.

    python3 tools/icon/make_icon.py
"""
import math
import os

# --- artwork ------------------------------------------------------------------
CX, CY = 60.0, 56.0     # eye of the curl
TURNS = 1.45            # how far the lip wraps
A = 4.2                 # spiral scale at the eye
B = 0.30                # growth rate
SQUASH_X, SQUASH_Y = 1.18, 0.86   # read as a wave, not a shell

SEA_TOP, SEA_MID, SEA_BOTTOM = "#04223A", "#083F63", "#0B5E7F"
FOAM_WHITE = "#EAFFFB"

# The wave bleeds off the canvas by design; 0.84 keeps the spiral itself clear
# of the adaptive-icon mask while preserving that bleed.
SAFE_SCALE = 0.84
SAFE_OFFSET = (108 - 108 * SAFE_SCALE) / 2


def spiral(t):
    r = A * math.exp(B * t)
    return CX + r * math.cos(t) * SQUASH_X, CY - r * math.sin(t) * SQUASH_Y


def _sample(t0, t1, n=140):
    return [spiral(t0 + (t1 - t0) * i / n) for i in range(n + 1)]


def _path(points):
    return ("M{:.2f},{:.2f}".format(*points[0])
            + "".join(" L{:.2f},{:.2f}".format(*p) for p in points[1:])
            + " Z")


def _ribbon(t0, inner_ratio):
    """Spiral band from t0 out to the lip, `inner_ratio` of the way back in."""
    outer = _sample(t0, TURNS * 2 * math.pi)
    inner = [(CX + (x - CX) * inner_ratio, CY + (y - CY) * inner_ratio)
             for x, y in reversed(outer)]
    return _path(outer + inner)


def barrel():
    """The body of the curl."""
    return _ribbon(-0.55 * math.pi, 0.62)


def lip():
    """Foam riding the outside of the curl."""
    return _ribbon(0.35 * math.pi, 0.90)


def face():
    """The wave face falling away from the curl into the trough."""
    lx, ly = spiral(TURNS * 2 * math.pi)
    return ("M{:.2f},{:.2f} ".format(lx, ly)
            + "C 84,52 78,74 60,86 C 44,96 22,96 8,90 "
            + "C 8,90 16,74 30,64 C 42,55 54,46 {:.2f},{:.2f} Z".format(lx - 2, ly + 2))


FOAM = ("M6,92 C20,84 34,88 46,92 C58,96 72,94 84,88 "
        "C84,88 78,100 62,102 C44,104 22,100 6,92 Z")


def spray():
    """Droplets thrown off the lip, largest nearest the crest."""
    lx, ly = spiral(TURNS * 2 * math.pi)
    offsets = [(6, -9, 3.1), (14, -4, 2.2), (10, -17, 2.0), (20, -12, 1.5), (2, -19, 1.4)]
    return [(lx + dx, ly + dy, r, round(0.95 - i * 0.12, 2))
            for i, (dx, dy, r) in enumerate(offsets)]


def circle_path(x, y, r):
    """Android vectors have no circle element -- two arcs make one."""
    return "M{:.2f},{:.2f} a{:.2f},{:.2f} 0 1,0 {:.2f},0 a{:.2f},{:.2f} 0 1,0 {:.2f},0 Z".format(
        x - r, y, r, r, 2 * r, r, r, -2 * r)


# --- SVG ----------------------------------------------------------------------
def svg(with_background: bool) -> str:
    drops = "".join(
        f'<circle cx="{x:.2f}" cy="{y:.2f}" r="{r}" fill="{FOAM_WHITE}" opacity="{o}"/>'
        for x, y, r, o in spray()
    )
    bg = ('<rect width="108" height="108" fill="url(#sea)"/>'
          '<circle cx="80" cy="26" r="15" fill="url(#sun)" opacity="0.55"/>'
          if with_background else "")
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="512" height="512">
<defs>
 <linearGradient id="sea" x1="0" y1="0" x2="0.3" y2="1">
  <stop offset="0" stop-color="{SEA_TOP}"/><stop offset="0.55" stop-color="{SEA_MID}"/>
  <stop offset="1" stop-color="{SEA_BOTTOM}"/></linearGradient>
 <radialGradient id="sun" cx="0.5" cy="0.5" r="0.5">
  <stop offset="0" stop-color="#FFD79A"/><stop offset="1" stop-color="#FFD79A" stop-opacity="0"/></radialGradient>
 <linearGradient id="wave" x1="0.1" y1="0" x2="0.8" y2="1">
  <stop offset="0" stop-color="#7BF7E4"/><stop offset="0.45" stop-color="#2BE3C6"/>
  <stop offset="1" stop-color="#0E86A8"/></linearGradient>
 <linearGradient id="faceGrad" x1="0" y1="0" x2="0.4" y2="1">
  <stop offset="0" stop-color="#1FB6C9"/><stop offset="1" stop-color="#0A4C77"/></linearGradient>
</defs>
{bg}
<path d="{face()}" fill="url(#faceGrad)"/>
<path d="{barrel()}" fill="url(#wave)"/>
<path d="{lip()}" fill="{FOAM_WHITE}" opacity="0.92"/>
<path d="{FOAM}" fill="{FOAM_WHITE}" opacity="0.88"/>
{drops}
</svg>"""


# --- Android vector drawables --------------------------------------------------
def foreground() -> str:
    drops = "\n".join(
        f'    <path android:pathData="{circle_path(x, y, r)}" '
        f'android:fillColor="{FOAM_WHITE}" android:fillAlpha="{o}"/>'
        for x, y, r, o in spray()
    )
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/icon/make_icon.py; edit the artwork there, not here. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
  <group
      android:scaleX="{SAFE_SCALE}"
      android:scaleY="{SAFE_SCALE}"
      android:translateX="{SAFE_OFFSET:.2f}"
      android:translateY="{SAFE_OFFSET:.2f}">

    <path android:pathData="{face()}">
      <aapt:attr name="android:fillColor">
        <gradient android:type="linear"
            android:startX="8" android:startY="40" android:endX="52" android:endY="100">
          <item android:offset="0" android:color="#FF1FB6C9"/>
          <item android:offset="1" android:color="#FF0A4C77"/>
        </gradient>
      </aapt:attr>
    </path>

    <path android:pathData="{barrel()}">
      <aapt:attr name="android:fillColor">
        <gradient android:type="linear"
            android:startX="11" android:startY="8" android:endX="86" android:endY="100">
          <item android:offset="0" android:color="#FF7BF7E4"/>
          <item android:offset="0.45" android:color="#FF2BE3C6"/>
          <item android:offset="1" android:color="#FF0E86A8"/>
        </gradient>
      </aapt:attr>
    </path>

    <path android:pathData="{lip()}" android:fillColor="{FOAM_WHITE}" android:fillAlpha="0.92"/>
    <path android:pathData="{FOAM}" android:fillColor="{FOAM_WHITE}" android:fillAlpha="0.88"/>
{drops}
  </group>
</vector>
"""


def background() -> str:
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/icon/make_icon.py -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
  <path android:pathData="M0,0h108v108h-108z">
    <aapt:attr name="android:fillColor">
      <gradient android:type="linear"
          android:startX="0" android:startY="0" android:endX="32" android:endY="108">
        <item android:offset="0" android:color="#FF{SEA_TOP[1:]}"/>
        <item android:offset="0.55" android:color="#FF{SEA_MID[1:]}"/>
        <item android:offset="1" android:color="#FF{SEA_BOTTOM[1:]}"/>
      </gradient>
    </aapt:attr>
  </path>
  <path android:pathData="{circle_path(80, 26, 17)}">
    <aapt:attr name="android:fillColor">
      <gradient android:type="radial" android:centerX="80" android:centerY="26"
          android:gradientRadius="17">
        <item android:offset="0" android:color="#8CFFD79A"/>
        <item android:offset="1" android:color="#00FFD79A"/>
      </gradient>
    </aapt:attr>
  </path>
</vector>
"""


def monochrome() -> str:
    """Themed-icon layer: a flat white silhouette that the launcher tints itself.

    No `?attr/colorControlNormal` here -- that attribute belongs to AppCompat and
    this app themes off the framework, so referencing it fails resource linking.
    """
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/icon/make_icon.py -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
  <group
      android:scaleX="{SAFE_SCALE}"
      android:scaleY="{SAFE_SCALE}"
      android:translateX="{SAFE_OFFSET:.2f}"
      android:translateY="{SAFE_OFFSET:.2f}">
    <path android:pathData="{barrel()}" android:fillColor="#FFFFFFFF"/>
    <path android:pathData="{FOAM}" android:fillColor="#FFFFFFFF"/>
  </group>
</vector>
"""


def main():
    os.makedirs("tools/icon", exist_ok=True)
    open("tools/icon/olakai.svg", "w").write(svg(True))
    open("tools/icon/olakai-foreground.svg", "w").write(svg(False))

    res = "app/src/main/res"
    os.makedirs(f"{res}/drawable", exist_ok=True)
    open(f"{res}/drawable/ic_launcher_foreground.xml", "w").write(foreground())
    open(f"{res}/drawable/ic_launcher_background.xml", "w").write(background())
    open(f"{res}/drawable/ic_launcher_monochrome.xml", "w").write(monochrome())
    print("wrote icon SVGs and Android vector drawables")


if __name__ == "__main__":
    main()
