#!/usr/bin/env python3
"""Build app/src/main/assets/spots.json.

Place descriptions live here rather than in the app so they can be edited and
regenerated without touching Kotlin. Cams are NOT written here -- they come from
resolve_cams.py into cams.json and get merged at runtime.
"""
import json, datetime

def s(id, name, region, country, cc, lat, lon, tz, tags, about, brk, bottom, wave,
      level, swell, wind, tide, season, water, crowd, hazards, tip,
      airports, transfer, mins, visa=""):
    return {
        "id": id, "name": name, "region": region, "country": country,
        "countryCode": cc, "lat": lat, "lon": lon, "timezone": tz, "tags": tags,
        "info": {
            "about": about, "breakType": brk, "bottom": bottom, "wave": wave,
            "level": level, "bestSwell": swell, "bestWind": wind, "bestTide": tide,
            "bestSeason": season, "waterTemp": water, "crowd": crowd,
            "hazards": hazards, "localTip": tip,
        },
        "access": {"airports": airports, "transfer": transfer,
                   "transferMinutes": mins, "visaNote": visa},
        # Real operator pages, generated from the spot's own coordinates. Every
        # spot gets these, so a place with no embeddable stream still has a
        # live-cam route instead of a dead end.
        "externalCams": [
            {"id": f"{id}-windy", "title": "Webcams near here (Windy)",
             "kind": "external", "source": f"https://www.windy.com/-Webcams/webcams?webcams,{lat},{lon},10",
             "provider": "Windy", "attribution": "Windy.com",
             "pageUrl": f"https://www.windy.com/-Webcams/webcams?webcams,{lat},{lon},10"},
            {"id": f"{id}-surfline", "title": "Surfline cam & report",
             "kind": "external", "source": f"https://www.surfline.com/search/{name.split('(')[0].strip().replace(' ', '%20')}",
             "provider": "Surfline", "attribution": "Surfline",
             "pageUrl": f"https://www.surfline.com/search/{name.split('(')[0].strip().replace(' ', '%20')}"},
        ],
    }

SPOTS = [
 s("pipeline","Banzai Pipeline","North Shore, Oahu","United States","US",21.6650,-158.0530,"Pacific/Honolulu",
   ["Reef","Barrel","Expert","Iconic"],
   "The most photographed wave on earth and the most consequential. Pipeline breaks over a shallow, cavernous lava reef only a few hundred metres off Ehukai Beach Park, throwing a thick left-hand barrel that ends in dry rock. Backdoor peels right off the same peak. When the North Pacific lights up between November and February the whole surfing world points its cameras here.",
   "Reef break","Shallow lava reef with caves","Heaving left barrel; Backdoor is the right","Expert only",
   "NW–N groundswell, 8–15 ft faces","Light E/NE trades or glassy dawn","All tides; low is heaviest",
   "November–February","24–27°C (75–80°F), trunks year round","Extreme in season — a strict pecking order",
   ["Shallow reef with undercut caves","Heavy hold-downs","Localised crowd — respect the order"],
   "Watch a full set from the beach before paddling. If you are asking whether you are ready, you are not.",
   ["HNL"],"About 60 min by car from Honolulu up the H-2 and Kam Highway",60,
   "US ESTA/visa required for most non-US visitors"),

 s("waimea","Waimea Bay","North Shore, Oahu","United States","US",21.6420,-158.0650,"Pacific/Honolulu",
   ["Big wave","Reef","Expert"],
   "The birthplace of modern big-wave surfing. Waimea sleeps flat most of the year, then wakes up when the North Pacific sends 20-foot-plus swell, producing a giant right-hand peak that breaks into a deepwater bay. The Eddie Aikau invitational runs here only when the bay says it can.",
   "Big-wave reef point","Deep sand over rock","Steep, fast drop into a bowling right","Expert only",
   "Huge NW–N groundswell (20 ft+ Hawaiian)","Light offshore E/SE","Any tide",
   "December–February","24–26°C","Small but elite lineup; huge shorebreak crowd on the sand",
   ["Deadly shorebreak","Strong rip out of the bay","Only ride it if you can swim it"],
   "The rip along the rocks on the north side is the standard paddle-out lane on big days.",
   ["HNL"],"About 55 min drive from Honolulu",55,
   "US ESTA/visa required for most non-US visitors"),

 s("sunset-beach","Sunset Beach","North Shore, Oahu","United States","US",21.6790,-158.0410,"Pacific/Honolulu",
   ["Reef","Big wave","Advanced"],
   "A huge, shifting right-hand peak over a wide reef, and the North Shore's most demanding paddle. Sunset rewards positioning over speed: the takeoff zone moves with every set and the West Bowl can turn a good wave into a great one. It has been a contest venue since the sport professionalised.",
   "Reef break","Coral and sand","Big, shifting right with a bowling inside section","Advanced to expert",
   "NW–N groundswell, 6–15 ft","E/NE trades","Any tide",
   "November–February","24–27°C","Busy but spread out over a big playing field",
   ["Powerful rips","Long paddle","Shifting peaks — sets swing wide"],
   "Line up off the point and be ready to scratch wide; the second wave of a set is usually the better one.",
   ["HNL"],"About 60 min drive from Honolulu",60,
   "US ESTA/visa required for most non-US visitors"),

 s("waikiki","Waikiki (Queens & Canoes)","Oahu","United States","US",21.2710,-157.8250,"Pacific/Honolulu",
   ["Longboard","Beginner","Reef"],
   "Where surfing was reintroduced to the world. Waikiki's outer reefs produce slow, forgiving rollers that can run for 200 metres or more, perfect for longboards and first waves. Duke Kahanamoku's statue faces the break he made famous, and the beachboy tradition of teaching visitors here is over a century old.",
   "Reef break","Flat coral reef","Long, mellow, gently sloping walls","Beginner to intermediate",
   "S–SW groundswell","Light NE trades (offshore here)","Mid to high tide is safest over the reef",
   "May–September (southern hemisphere swell)","25–27°C","Very busy but friendly and forgiving",
   ["Shallow coral on low tide","Outrigger canoes sharing the lineup","Sea urchins"],
   "Queens is the pick of the peaks; go at dawn before the catamarans and lessons arrive.",
   ["HNL"],"15 min from Honolulu airport",15,
   "US ESTA/visa required for most non-US visitors"),

 s("hookipa","Ho'okipa","Maui","United States","US",20.9330,-156.3570,"Pacific/Honolulu",
   ["Reef","Windsurf","Advanced"],
   "Maui's north-shore proving ground and the world capital of windsurfing. Ho'okipa has three reef peaks — Pavilions, Middles and Lanes — that handle serious size, and a cliff-top car park that makes it one of the best waves on earth to simply watch. Green sea turtles haul out on the beach most afternoons.",
   "Reef break","Lava reef","Punchy rights and lefts across three peaks","Advanced",
   "N–NE groundswell","Light SW or early morning glass","Mid tide",
   "October–April","24–26°C","Crowded; surfers have the morning, windsurfers take over after about 11am",
   ["Sharp lava reef","Strong current between peaks","Trade winds get violent by midday"],
   "Surf it before 11am. Local etiquette hands the water over to the sailors when the wind fills in.",
   ["OGG"],"About 20 min east of Kahului on the Hana Highway",20,
   "US ESTA/visa required for most non-US visitors"),

 s("huntington","Huntington Beach Pier","California","United States","US",33.6550,-118.0000,"America/Los_Angeles",
   ["Beach break","Contest","All levels"],
   "Surf City USA. A long stretch of consistent beach break either side of a concrete pier, with peaks that suit everyone from first-timers to the pros who show up for the US Open every summer. It is rarely world class and almost never flat, which is exactly why the whole industry grew up around it.",
   "Beach break","Sand","Peaky, punchy, both directions","All levels",
   "SW summer swell or NW winter swell","Light E/NE morning offshore","Mid tide, incoming",
   "Year round; biggest in winter","15–20°C — wetsuit most of the year","Very crowded, especially south of the pier",
   ["Rip currents","Pier pilings","Summer crowds and blackball flags"],
   "The sandbars either side of the pier shift constantly — walk the beach and pick your peak rather than paddling out where everyone else is.",
   ["SNA","LAX"],"20 min from John Wayne (SNA); about 50 min from LAX",20,
   "US ESTA/visa required for most non-US visitors"),

 s("malibu","Malibu (First Point)","California","United States","US",34.0320,-118.6790,"America/Los_Angeles",
   ["Point break","Longboard","Iconic"],
   "The most influential right-hand point in surfing. On a good south swell Malibu links three points into a single, tapering wall that can run the length of the beach — the wave that shaped longboarding, then shortboarding, then the entire California myth. It is also a designated World Surfing Reserve.",
   "Cobblestone point break","Cobblestone and sand","Long, tapered, machine-like right","Intermediate; crowded enough to demand skill",
   "S–SW groundswell","Light offshore NE or glassy","Medium to high, incoming",
   "May–September","16–20°C","Extreme — one of the most crowded waves in the world",
   ["Severe crowd and drop-ins","Rocks at the point","Water quality after rain"],
   "Third Point is where the wave starts; ride it through and you get the whole thing. Weekday dawn is the only quiet window.",
   ["LAX"],"About 45 min up the Pacific Coast Highway from LAX",45,
   "US ESTA/visa required for most non-US visitors"),

 s("steamer-lane","Steamer Lane","Santa Cruz, California","United States","US",36.9510,-122.0270,"America/Los_Angeles",
   ["Point break","Cold water","Advanced"],
   "A cliff-side right-hand point in the heart of Santa Cruz, with four distinct peaks and a natural amphitheatre of onlookers along West Cliff Drive. The Lane handles size, holds shape in wind that ruins everywhere else, and has been the proving ground for Northern Californian surfing since the 1930s.",
   "Reef/point break","Rock reef","Powerful right with a steep drop; Middle Peak holds size","Advanced",
   "W–NW groundswell","NE offshore or light","Mid to low",
   "October–March","11–15°C — 4/3 wetsuit and boots on cold days","Crowded and territorial",
   ["Cold water","Rocks and cliff","Great white sharks are present in the region"],
   "Watch from the lighthouse for twenty minutes first; each of the four peaks wants a different lineup.",
   ["SJC","SFO"],"About 45 min over the hill from San Jose",45,
   "US ESTA/visa required for most non-US visitors"),

 s("ocean-beach-sf","Ocean Beach","San Francisco, California","United States","US",37.7590,-122.5110,"America/Los_Angeles",
   ["Beach break","Heavy","Expert"],
   "Three miles of raw, cold, unforgiving beach break at the edge of San Francisco. The paddle out is legendary — multiple lines of whitewater, ferocious rips and water that rarely climbs out of the low teens. When it is good it is as heavy as any beach break in the world.",
   "Beach break","Sand","Thick, close-out prone A-frames; big and fast when it works","Expert",
   "NW groundswell, cleaner at 4–8 ft","E offshore, early","Lower tides hold better shape",
   "September–November has the cleanest windows","11–14°C — 4/3 with hood and boots in winter","Uncrowded, because it is hard",
   ["Brutal paddle out","Powerful rips","Cold water and fog","Sharks in the wider region"],
   "Use the rip to get out, never to come in. Sloat and Noriega break differently — check both.",
   ["SFO"],"25 min across the city from SFO",25,
   "US ESTA/visa required for most non-US visitors"),

 s("san-diego","San Diego (Blacks & PB)","California","United States","US",32.8790,-117.2520,"America/Los_Angeles",
   ["Beach break","Canyon","All levels"],
   "San Diego's coast runs from mellow Pacific Beach peaks to Blacks Beach, where the Scripps submarine canyon funnels swell into some of the most powerful beach break in California. Sun, consistency and a hundred kilometres of coastline make it the easiest place in the US to surf every day.",
   "Beach break over a submarine canyon","Sand","Powerful, wedging peaks at Blacks; softer at PB","Intermediate to advanced at Blacks",
   "W–NW winter or S summer swell","Light E offshore, morning","Mid tide",
   "Year round","15–21°C — spring suit to 3/2","Busy but spread across many beaches",
   ["Long, steep trail down to Blacks","Rip currents","Sun exposure"],
   "Blacks doubles in size relative to the rest of the coast — check the buoy, not the neighbouring beach.",
   ["SAN"],"20–30 min from San Diego airport",25,
   "US ESTA/visa required for most non-US visitors"),

 s("cocoa-beach","Cocoa Beach","Florida","United States","US",28.3600,-80.6070,"America/New_York",
   ["Beach break","Beginner","Warm water"],
   "Kelly Slater's home beach and the friendliest place in the US to learn. The Atlantic here delivers small, soft, warm-water peaks most of the year, going properly good when a hurricane swell or a winter nor'easter arrives. The pier is the landmark and the meeting point.",
   "Beach break","Sand","Small, soft, forgiving peaks","Beginner to intermediate",
   "E–NE swell; hurricane season brings the size","W offshore","Mid to high tide",
   "August–November for size; year round for learning","22–29°C — boardshorts most of the year","Busy near the pier, empty a mile either way",
   ["Long flat spells","Lightning storms in summer","Rip currents near the pier"],
   "When the forecast is flat here it usually is. Watch the tropics — a distant hurricane transforms this coast.",
   ["MCO","MLB"],"About 60 min east from Orlando; 20 min from Melbourne",60,
   "US ESTA/visa required for most non-US visitors"),

 s("sebastian-inlet","Sebastian Inlet","Florida","United States","US",27.8600,-80.4470,"America/New_York",
   ["Jetty","Performance","Intermediate"],
   "The best wave in Florida and the training ground of a generation of American professionals. The north jetty focuses swell into a fast, rampy right-hander — 'First Peak' — that is the closest thing the east coast has to a performance wave, and the contest site that produced Slater, Lopez and the Hobgoods.",
   "Jetty-assisted sandbar","Sand against rock jetty","Fast, wedging right with an air section","Intermediate to advanced",
   "E–NE swell","W–NW offshore","Mid tide, incoming",
   "September–April","21–28°C","Very crowded at First Peak; spread out down the beach",
   ["Strong inlet current","Sharks are common around the inlet","Tight, competitive lineup"],
   "If First Peak is a zoo, walk south — the beach picks up the same swell with a tenth of the crowd.",
   ["MLB","MCO"],"About 40 min south of Melbourne, FL",40,
   "US ESTA/visa required for most non-US visitors"),

 s("outer-banks","Outer Banks","North Carolina","United States","US",35.9080,-75.6200,"America/New_York",
   ["Beach break","Barrel","Hurricane swell"],
   "A 200-mile sandbar hanging off the American east coast, and the best beach break on it. When a hurricane tracks offshore in September the OBX sandbars produce genuinely world-class barrels; the rest of the year it is windswept, empty and wildly variable.",
   "Beach break","Sand","Hollow, fast, shifting peaks","Intermediate to advanced",
   "E–SE hurricane swell or winter NE","W–SW offshore","Low to mid",
   "August–October","10–27°C — full range across the seasons","Empty outside hurricane season",
   ["Powerful rips","Isolated stretches with no lifeguards","Sharks","Storm closures"],
   "Rent a car and drive: the sandbars change every storm and the best peak is rarely at the same milepost twice.",
   ["ORF"],"About 90 min south from Norfolk, Virginia",90,
   "US ESTA/visa required for most non-US visitors"),

 s("virginia-beach","Virginia Beach","Virginia","United States","US",36.8330,-75.9680,"America/New_York",
   ["Beach break","Pier","All levels"],
   "A long, sandy municipal beach with a pier at First Street that focuses whatever swell the mid-Atlantic offers. It is not a world-class wave but it is consistent, easy to access, and home to the East Coast Surfing Championships — the oldest continuously running surf contest in the world.",
   "Beach break","Sand","Short, punchy peaks near the pier","All levels",
   "NE winter swell or SE hurricane swell","W offshore","Mid tide",
   "September–November","6–27°C","Busy at the pier in summer",
   ["Rip currents","Summer swimming restrictions","Long flat spells in midsummer"],
   "The peaks right on the pier pilings are best but are usually closed to surfing in peak summer — check local flags.",
   ["ORF"],"25 min from Norfolk airport",25,
   "US ESTA/visa required for most non-US visitors"),

 s("puerto-escondido","Zicatela, Puerto Escondido","Oaxaca","Mexico","MX",15.8480,-97.0580,"America/Mexico_City",
   ["Beach break","Big wave","Expert"],
   "The Mexican Pipeline: the heaviest beach break on the planet. A deep offshore trench lets long-period South Pacific swell march straight into the sand at Zicatela, unloading in giant, square barrels that regularly top 20 feet. It is a big-wave venue that happens to break on a beach.",
   "Beach break","Sand over a steep shelf","Enormous, square, sand-bottom barrels","Expert only",
   "S–SW long-period groundswell","N offshore, early morning","All tides",
   "April–September","27–30°C — boardshorts","Small crew of specialists; heavy respect required",
   ["Extremely powerful waves","Vicious rips and a brutal shorebreak","Deaths occur here most seasons"],
   "La Punta at the south end is the friendly wave; Zicatela is not. Know the difference before you paddle.",
   ["PXM","HUX"],"10 min from Puerto Escondido airport; about 2.5h from Huatulco",10,
   "Most nationalities get a visa on arrival for Mexico"),

 s("sayulita","Sayulita","Nayarit","Mexico","MX",20.8690,-105.4410,"America/Mexico_City",
   ["Beach break","Beginner","Warm water"],
   "A cobblestone town on Banderas Bay that turned a gentle right-hand point into a whole surf-school economy. The wave is soft, warm and forgiving, the town is full of taco stands and hammocks, and the harder waves at Punta Mita and Burros are twenty minutes up the road.",
   "Point/beach break","Sand and cobble","Slow, mellow rights and a shorter left","Beginner to intermediate",
   "S–SW or NW swell","Light E offshore","Mid tide",
   "December–April for the cleanest conditions","26–29°C","Very busy with schools; go early",
   ["Crowds of beginners on soft-tops","Water quality after heavy rain","Stingrays — shuffle your feet"],
   "Paddle 20 minutes north to Carricitos or drive to La Lancha for the same swell without the school crowd.",
   ["PVR"],"About 50 min north from Puerto Vallarta",50,
   "Most nationalities get a visa on arrival for Mexico"),

 s("tamarindo","Tamarindo","Guanacaste","Costa Rica","CR",10.2990,-85.8420,"America/Costa_Rica",
   ["Beach break","Rivermouth","All levels"],
   "Guanacaste's surf hub: a wide, sandy bay with a rivermouth sandbar, warm water year round and an easy inside section that has taught thousands of people to surf. Witch's Rock and Ollie's Point are a boat ride north, which is why so many trips base themselves here.",
   "Beach break with a rivermouth bank","Sand","Long, soft rights on the rivermouth; peaky beach break inside","Beginner to intermediate",
   "SW groundswell","E offshore in the dry season","Mid to high",
   "April–October for swell; December–April for offshore wind","27–29°C","Busy but the bay is wide enough",
   ["Crocodiles in the estuary — do not cross the rivermouth","Strong rip on the north side","Theft from parked cars"],
   "Book a panga to Witch's Rock for a dawn session; it is one of the great day trips in surfing.",
   ["LIR","SJO"],"About 75 min from Liberia; roughly 5h from San José",75,
   "Most nationalities get 90 days visa-free in Costa Rica"),

 s("santa-teresa","Santa Teresa","Nicoya Peninsula","Costa Rica","CR",9.6430,-85.1660,"America/Costa_Rica",
   ["Beach break","Consistent","All levels"],
   "A dirt-road beach town on the tip of the Nicoya Peninsula with kilometres of consistent, punchy beach break and some of the most reliable offshore mornings in Central America. It went from fishing village to international surf destination in about fifteen years and the swell has never noticed.",
   "Beach break","Sand","Punchy A-frames, hollow at low tide","Intermediate; beginner-friendly sections",
   "SW groundswell","E–NE offshore most mornings","Mid tide rising; low is hollow",
   "April–October","27–29°C","Spread along a long beach — easy to find space",
   ["Strong rips","Rough access roads","Sun exposure — very little shade"],
   "The bank in front of Playa Carmen is the most consistent; walk north toward Playa Hermosa for cleaner peaks.",
   ["SJO"],"About 5h by road plus ferry from San José, or a 40-min light aircraft hop to Tambor",300,
   "Most nationalities get 90 days visa-free in Costa Rica"),

 s("punta-de-lobos","Punta de Lobos","Pichilemu","Chile","CL",-34.4180,-72.0430,"America/Santiago",
   ["Point break","Big wave","Cold water"],
   "Chile's most famous wave: a long, powerful left-hand point that peels past two sea stacks below dramatic cliffs. It handles huge swell, has hosted big-wave events, and is protected as a World Surfing Reserve after a local campaign saved the headland from development.",
   "Point break","Rock and boulder","Long, powerful, walling left","Advanced",
   "SW–W groundswell — almost always on","S–SE offshore","Mid tide",
   "April–September for size; year round consistency","13–17°C — 4/3 wetsuit","Moderate; the wave is long enough to share",
   ["Cold water","Sharp rocks on the jump-off","Very strong current on big days","Remote — limited medical help"],
   "The jump-off from the rocks is the standard entry; time it with the sets rather than fighting the paddle from the beach.",
   ["SCL"],"About 3.5h south-west by road from Santiago",210,
   "Many nationalities enter Chile visa-free for 90 days"),

 s("florianopolis","Florianópolis","Santa Catarina","Brazil","BR",-27.6280,-48.4270,"America/Sao_Paulo",
   ["Beach break","Island","All levels"],
   "An island with more than forty beaches and a wave for every wind. Joaquina is the contest beach and the birthplace of Brazilian competitive surfing; Praia Mole, Campeche and Silveira spread the crowd across the island. Brazil's surf industry effectively lives here.",
   "Beach breaks and points","Sand","Punchy, rippable peaks","All levels — pick your beach",
   "S–SE groundswell","N–NW offshore for the east-coast beaches","Mid tide",
   "April–September","18–25°C — spring suit to 3/2","Busy in summer; quiet mid-week in winter",
   ["Strong rips at Joaquina","Summer holiday crowds","Urban water quality in some bays"],
   "With this many beaches, let the wind pick the spot — there is almost always somewhere offshore on the island.",
   ["FLN"],"20–40 min by car depending on which beach",30,
   "Check Brazil's current visa rules for your nationality"),

 s("rio","Rio de Janeiro","Rio de Janeiro","Brazil","BR",-22.9880,-43.1900,"America/Sao_Paulo",
   ["Beach break","City","All levels"],
   "Surfing under the Christ statue. Arpoador, the rock between Ipanema and Copacabana, is the city's best-known peak — a short, punchy right with a sunset ritual and a permanent crowd. Barra and Recreio down the coast take more swell and give more room.",
   "Beach break","Sand","Short, sharp, wedging peaks","Intermediate",
   "S–SE swell","N offshore","Mid to high tide",
   "April–October","20–26°C","Arpoador is packed; Recreio is not",
   ["Very crowded lineup","Urban water quality after rain","Petty theft on the beach — take nothing"],
   "Arpoador at sunrise is the session; the rock gets a round of applause at sunset for a reason.",
   ["GIG"],"About 45 min from Galeão to the south-zone beaches",45,
   "Check Brazil's current visa rules for your nationality"),

 s("nazare","Nazaré (Praia do Norte)","Leiria","Portugal","PT",39.6050,-9.0850,"Europe/Lisbon",
   ["Big wave","Tow","Spectacle"],
   "The biggest rideable waves ever surfed. An underwater canyon 5km deep funnels North Atlantic swell straight into the headland at Praia do Norte, focusing it into peaks that have exceeded 25 metres. Most people come to watch from the lighthouse fort — which is the right call.",
   "Canyon-focused beach break","Sand","Enormous, chaotic, shifting peaks","Tow-in professionals only",
   "Huge NW Atlantic groundswell with long period","E–NE offshore","All tides",
   "October–March","14–18°C — 4/3 wetsuit","Tiny water crew; enormous crowd on the cliff",
   ["Lethal for anyone but professionals with ski support","Violent shorebreak","Cliff-edge viewing areas"],
   "Watch from Forte de São Miguel Arcanjo. For actually surfing, Praia do Sul in town is the sane option.",
   ["LIS"],"About 90 min north of Lisbon by motorway",90,
   "Schengen area — check your entry requirements"),

 s("ericeira","Ericeira","Lisboa","Portugal","PT",38.9630,-9.4180,"Europe/Lisbon",
   ["Reef","World Surfing Reserve","Advanced"],
   "Europe's only World Surfing Reserve: seven world-class reefs inside four kilometres of coast. Ribeira d'Ilhas is the long, rippable right that hosts contests; Coxos is the heavy one the locals guard; Pedra Branca is the barrel. A fishing town that became the best-value surf trip in Europe.",
   "Reef points","Rock reef","Long walling rights at Ribeira; hollow and heavy at Coxos","Intermediate to expert depending on the reef",
   "NW–W groundswell","N–NE offshore","Mid tide; Coxos prefers higher",
   "September–April","15–19°C — 3/2 to 4/3","Busy at Ribeira, guarded at Coxos",
   ["Sharp reef and urchins","Rock entries","Localism at the heavier reefs"],
   "Start at Ribeira d'Ilhas. Earn Coxos later, and only when it is not crowded with locals.",
   ["LIS"],"About 50 min north-west of Lisbon",50,
   "Schengen area — check your entry requirements"),

 s("peniche","Supertubos, Peniche","Leiria","Portugal","PT",39.3480,-9.3660,"Europe/Lisbon",
   ["Beach break","Barrel","Advanced"],
   "The European Pipeline. Supertubos is a sand-bottom beach break that throws thick, fast, perfectly round barrels when a NW swell meets the right bank — heavy enough to hold a championship-tour event. Peniche's peninsula also means there is a beach facing every wind direction.",
   "Beach break","Sand over a steep shelf","Thick, fast, hollow barrels","Advanced",
   "NW groundswell, 3–8 ft","E–NE offshore","Low to mid, incoming",
   "October–March","14–18°C — 4/3","Crowded when it is on",
   ["Heavy, sand-sucking barrels","Board-breaking closeouts","Strong rips"],
   "If Supertubos is closing out, drive ten minutes to Baleal — the peninsula almost always has a sheltered option.",
   ["LIS"],"About 75 min north of Lisbon",75,
   "Schengen area — check your entry requirements"),

 s("caparica","Costa da Caparica","Setúbal","Portugal","PT",38.6470,-9.2340,"Europe/Lisbon",
   ["Beach break","City escape","All levels"],
   "Lisbon's home beach: 15 kilometres of sand break starting a bridge-crossing from the city centre. A series of groynes creates dozens of banks, so there is nearly always a peak with space, and the whole coast is reachable on public transport from the capital.",
   "Beach break","Sand between groynes","Peaky, consistent, medium power","All levels",
   "NW–W swell","N–NE offshore","Mid tide",
   "September–May","15–19°C — 3/2 to 4/3","Busy near the town, empty further south",
   ["Rips between the groynes","Summer beach crowds","Occasional water quality issues after storms"],
   "Take the beach train south in summer — the further you go, the emptier and cleaner the banks.",
   ["LIS"],"About 30 min from Lisbon across the 25 de Abril bridge",30,
   "Schengen area — check your entry requirements"),

 s("mundaka","Mundaka","Basque Country","Spain","ES",43.4070,-2.6980,"Europe/Madrid",
   ["Rivermouth","Left","Expert"],
   "The best left-hand rivermouth in Europe, and possibly the world. When a big NW swell meets the sandbar at the mouth of the Urdaibai estuary, Mundaka produces a long, hollow, spinning left that can run for 400 metres. It is fickle, tide-dependent and worth the wait.",
   "Rivermouth sandbar","Sand over an estuary bar","Long, fast, barrelling left","Advanced to expert",
   "Big NW groundswell","S–SE offshore","Mid-to-low outgoing tide is the classic window",
   "September–March","13–18°C — 4/3 wetsuit","Very crowded and strictly hierarchical when it is on",
   ["Powerful outgoing current","Cold water","Strong local pecking order — wait your turn"],
   "The jetty jump-off saves a brutal paddle. If it is firing, expect a full lineup of very good local surfers.",
   ["BIO"],"About 45 min east from Bilbao",45,
   "Schengen area — check your entry requirements"),

 s("zarautz","Zarautz","Basque Country","Spain","ES",43.2860,-2.1710,"Europe/Madrid",
   ["Beach break","Consistent","All levels"],
   "The Basque country's longest beach and its most consistent, a 2.5km arc that picks up almost any swell and has been hosting European contests for decades. The town behind it is a pintxos crawl, which makes it an unusually civilised place to base a surf trip.",
   "Beach break","Sand","Consistent peaks, mellow to punchy","All levels",
   "NW–W swell","S offshore","Mid to low tide",
   "September–May","13–20°C — 3/2 to 4/3","Busy in town, quieter at either end",
   ["Rip currents","Summer crowds","Water can be choppy in onshore winds"],
   "The west end near the campsite has the best banks; the east end is calmer for learning.",
   ["EAS","BIO"],"About 25 min from San Sebastián; 60 min from Bilbao",25,
   "Schengen area — check your entry requirements"),

 s("san-sebastian","Zurriola, San Sebastián","Basque Country","Spain","ES",43.3230,-1.9740,"Europe/Madrid",
   ["Beach break","City","All levels"],
   "A surf beach in the middle of one of Europe's great food cities. Zurriola sits right in San Sebastián, exposed enough to pick up swell that the sheltered La Concha bay never sees, with a wall of pintxos bars two streets back from the sand.",
   "Beach break","Sand","Punchy, shifting peaks","Intermediate; beginner areas at the west end",
   "NW–N swell","S offshore","Mid tide",
   "September–May","13–21°C","Busy — it is a city beach",
   ["Rips near the river mouth","Crowded lineup","Water quality after heavy rain"],
   "Surf at dawn, eat pintxos in the Parte Vieja at night. That is the whole itinerary and it is a good one.",
   ["EAS","BIO"],"20 min from Hondarribia (EAS); 90 min from Bilbao",20,
   "Schengen area — check your entry requirements"),

 s("hossegor","Hossegor","Landes","France","FR",43.6620,-1.4400,"Europe/Paris",
   ["Beach break","Barrel","Advanced"],
   "The best beach break in Europe. The Gouf de Capbreton — a deep submarine canyon running right up to the shore — supercharges Atlantic swell into thick, hollow barrels at La Gravière and the surrounding banks. Europe's surf industry is headquartered here for a reason.",
   "Beach break over a submarine canyon","Sand","Thick, heavy, barrelling peaks","Advanced to expert",
   "W–NW groundswell","E offshore","Low to mid, rising",
   "September–October is the classic season","15–22°C — 3/2, 4/3 in winter","Crowded in season",
   ["Very heavy waves for a beach break","Strong rips","Banks shift constantly"],
   "September is the sweet spot: warm water, big Atlantic swell and offshore mornings. Check the banks daily.",
   ["BIQ"],"About 35 min north of Biarritz",35,
   "Schengen area — check your entry requirements"),

 s("biarritz","Biarritz","Nouvelle-Aquitaine","France","FR",43.4830,-1.5590,"Europe/Paris",
   ["Beach break","Longboard","All levels"],
   "Where European surfing began, in 1957, when a Hollywood screenwriter left a board behind. The Grande Plage sits below belle-époque hotels and a casino; Côte des Basques is the longboard beach at low tide; Marbella and Milady take the swell when it gets big.",
   "Beach breaks and reefs","Sand and rock","Mellow longboard walls to punchy beach peaks","All levels",
   "W–NW swell","E–SE offshore","Côte des Basques needs low tide",
   "September–November","14–22°C","Busy in summer, pleasant in autumn",
   ["Rocks at low tide on some beaches","Summer crowds","Rips on bigger days"],
   "Côte des Basques at low tide on a small clean swell is one of the nicest longboard sessions in Europe.",
   ["BIQ"],"10 min from Biarritz airport",10,
   "Schengen area — check your entry requirements"),

 s("lacanau","Lacanau Océan","Gironde","France","FR",45.0000,-1.2010,"Europe/Paris",
   ["Beach break","Consistent","All levels"],
   "A pine-forest beach town north of Bordeaux with a long, consistent stretch of Atlantic beach break and a European contest pedigree. Less heavy than Hossegor, more forgiving, and backed by 100km of cycle paths through the forest.",
   "Beach break","Sand","Consistent, medium-power peaks","All levels",
   "W–NW swell","E offshore","Mid tide",
   "May–October","14–22°C","Busy in July and August only",
   ["Rip currents","Banks change with every storm","Strong summer sun"],
   "Ride a bike north from the town centre and pick an empty bank — there are kilometres of them.",
   ["BOD"],"About 60 min west from Bordeaux",60,
   "Schengen area — check your entry requirements"),

 s("fistral","Fistral Beach, Newquay","Cornwall","United Kingdom","GB",50.4160,-5.1000,"Europe/London",
   ["Beach break","Contest","All levels"],
   "The centre of British surfing. Fistral faces straight into Atlantic swell, holds size better than most UK beaches, and has hosted the country's major contests for decades. The Cribbar, the big-wave reef off the headland, only shows up a few days a year.",
   "Beach break","Sand","Punchy peaks; holds size at North Fistral","All levels",
   "W–NW Atlantic swell","E–SE offshore","Mid tide",
   "September–November","10–17°C — 4/3 winter, 3/2 summer","Busy, especially in summer",
   ["Cold water","Rip currents","Very crowded in peak season"],
   "When Fistral is blown out, cross the peninsula to Watergate Bay or head to the north coast's sheltered coves.",
   ["NQY"],"10 min from Newquay Cornwall airport",10,
   "Check UK entry requirements for your nationality"),

 s("bundoran","Bundoran","Donegal","Ireland","IE",54.4780,-8.2870,"Europe/Dublin",
   ["Reef","Cold water","Advanced"],
   "Ireland's surf capital, on the wild Atlantic coast of Donegal. The Peak is a heavy left and right reef right in front of town, and the surrounding coast hides some of the heaviest slabs in Europe. Cold, raw and consistently good from autumn onwards.",
   "Reef break","Rock reef","Hollow, powerful left and right off a reef","Advanced",
   "W–NW Atlantic groundswell","E–SE offshore","Mid tide",
   "September–April","8–15°C — 5/4 with hood, gloves and boots in winter","Small, dedicated crew",
   ["Very cold water","Sharp reef","Powerful Atlantic swell","Short winter daylight"],
   "Bring the warmest wetsuit you own. The Atlantic here does not care what the calendar says.",
   ["NOC","DUB"],"About 60 min from Knock; roughly 3h from Dublin",60,
   "Ireland is outside Schengen — check entry requirements"),

 s("lahinch","Lahinch","Clare","Ireland","IE",52.9330,-9.3450,"Europe/Dublin",
   ["Beach break","Reef","All levels"],
   "A friendly beach break in a golf-and-surf town on the Clare coast, twenty minutes from the Cliffs of Moher. The beach is forgiving and good for learning; the reefs either side — including the notorious Aileen's under the cliffs — are anything but.",
   "Beach break with reefs nearby","Sand; rock at the reefs","Mellow beach peaks; heavy reefs on the flanks","Beginner on the beach, expert on the reefs",
   "W–NW Atlantic swell","E offshore","Mid to high tide on the beach",
   "September–April","9–16°C — 5/4 in winter","Relaxed",
   ["Cold water","Powerful reefs nearby — do not wander onto them","Strong currents at the river end"],
   "The beach is a genuinely good place to learn. Aileen's, under the Cliffs of Moher, is not a place to visit casually.",
   ["SNN"],"About 60 min from Shannon",60,
   "Ireland is outside Schengen — check entry requirements"),

 s("fuerteventura","Fuerteventura (North Shore)","Canary Islands","Spain","ES",28.7420,-13.8640,"Atlantic/Canary",
   ["Reef","Volcanic","Advanced"],
   "The Canaries' windswept desert island, with a north shore full of reefs — Hierro, Bristol, Mejillones, Generosa — that fire on winter Atlantic swell. Warm water, volcanic rock and a lunar landscape; the trade winds that make it a windsurfing capital also ruin the surf if you time it wrong.",
   "Reef breaks","Sharp volcanic reef","Fast, hollow rights and lefts","Advanced",
   "NW Atlantic groundswell","S–SE offshore","Mid tide",
   "October–March","18–23°C — 3/2 shorty to 3/2","Busy on the good reefs in winter",
   ["Very sharp volcanic reef — booties are common","Strong currents","Sea urchins","Rental-car break-ins at remote spots"],
   "The whole north shore is reef. Get a good pair of booties and study the entry and exit before you paddle out.",
   ["FUE"],"About 45 min north from Fuerteventura airport to Corralejo",45,
   "Schengen area — check your entry requirements"),

 s("lanzarote","Lanzarote (Famara & La Santa)","Canary Islands","Spain","ES",29.1170,-13.5560,"Atlantic/Canary",
   ["Reef","Beach break","All levels"],
   "A volcanic island where a 6km beach under a 600m cliff (Famara) sits half an hour from El Quemao, the Canaries' most serious barrel. Warm water in winter, consistent Atlantic swell, and a landscape that looks like another planet.",
   "Beach break and reefs","Sand at Famara; lava reef at La Santa","Mellow at Famara; heavy barrels at El Quemao","Beginner at Famara, expert at El Quemao",
   "NW Atlantic groundswell","E–SE offshore","Mid tide",
   "October–March","18–23°C","Famara is busy with schools; the reefs are guarded",
   ["Sharp lava reef","Strong currents at La Santa","El Quemao is for experts only","Sea urchins"],
   "Famara for learning and long days; El Quemao only if you genuinely belong there.",
   ["ACE"],"About 35 min from Arrecife to Famara",35,
   "Schengen area — check your entry requirements"),

 s("tenerife","Tenerife (Las Américas)","Canary Islands","Spain","ES",28.0730,-16.7350,"Atlantic/Canary",
   ["Reef","Volcanic","Intermediate"],
   "The south of Tenerife has a run of punchy lava reefs — Las Américas, La Fitenia, Spanish Left — that work on winter NW swell in T-shirt water. It is the most accessible Canarian surf, with an airport, a resort strip and reef breaks in the same square kilometre.",
   "Reef break","Lava reef and boulders","Fast, punchy rights and lefts","Intermediate to advanced",
   "NW swell","NE trade winds can be offshore on some reefs","Mid tide",
   "November–March","19–23°C — shorty or 3/2","Crowded on the accessible reefs",
   ["Sharp lava rock","Urchins","Rocky entries and exits","Strong currents"],
   "Booties are worth packing. The reefs are shallow and the rock is volcanic glass in places.",
   ["TFS"],"About 20 min from Tenerife South airport",20,
   "Schengen area — check your entry requirements"),

 s("taghazout","Taghazout & Anchor Point","Souss-Massa","Morocco","MA",30.5450,-9.7100,"Africa/Casablanca",
   ["Point break","Right","Advanced"],
   "A former fishing village turned surf town, with a run of long right-hand points down the coast. Anchor Point is the jewel — a 500-metre wall over boulders that works on winter NW swell — and Killer Point, Boilers and Panorama are all within a short drive.",
   "Point break","Boulder and rock","Long, walling, fast rights","Intermediate to advanced",
   "NW Atlantic groundswell","E offshore most winter mornings","Mid tide",
   "November–March","17–21°C — 3/2 wetsuit","Busy in peak season; the points are long enough to absorb it",
   ["Rocky entries and exits","Strong current down the point","Sea urchins","Sun and dehydration"],
   "The rock jump at Anchor Point is the fast way out. Watch a local do it once before you try.",
   ["AGA"],"About 45 min north from Agadir",45,
   "Many nationalities enter Morocco visa-free for 90 days"),

 s("jeffreys-bay","Jeffreys Bay (Supertubes)","Eastern Cape","South Africa","ZA",-34.0330,24.9300,"Africa/Johannesburg",
   ["Point break","Right","Expert"],
   "The most perfect right-hand point on earth. Supertubes runs down a rock ledge in a series of named sections — Boneyards, Supers, Impossibles, Tubes — that on the right day link into a 400-metre high-speed barrel. Championship tour venue, and the standard every other right is measured against.",
   "Point break","Rock reef","Fast, hollow, endlessly running right","Advanced to expert",
   "SW–S groundswell","W–NW offshore","All tides; mid is the classic",
   "June–September","14–20°C — 4/3 in winter","Very crowded when it is on, with a strict order",
   ["Fast, shallow sections","Great white sharks are present","Strong current down the point","Cold winter water"],
   "Paddle out at Boneyards and let the current do the work. Do not drop in — this lineup polices itself.",
   ["PLZ"],"About 60 min west from Gqeberha (Port Elizabeth)",60,
   "Many nationalities get 90 days visa-free in South Africa"),

 s("muizenberg","Muizenberg","Cape Town","South Africa","ZA",-34.1080,18.4700,"Africa/Johannesburg",
   ["Beach break","Beginner","Iconic"],
   "Cape Town's learn-to-surf beach, with its row of candy-coloured bathing boxes and a long, gentle sandbank that has been teaching people to stand up since the 1910s. Table Mountain is the backdrop and the water is a good deal warmer than the Atlantic side of the peninsula.",
   "Beach break","Sand","Long, slow, forgiving rights and lefts","Beginner to intermediate",
   "S–SW swell wrapping into False Bay","NW offshore","Mid tide",
   "April–September","14–20°C — 3/2 to 4/3","Very busy with schools",
   ["Great white sharks in False Bay — heed the shark spotters' flags","Rip near the river mouth","Crowded beginner zone"],
   "The shark spotters on the mountain fly flags for a reason. Learn the flag system before you paddle out.",
   ["CPT"],"About 40 min from Cape Town airport",40,
   "Many nationalities get 90 days visa-free in South Africa"),

 s("uluwatu","Uluwatu","Bali","Indonesia","ID",-8.8150,115.0880,"Asia/Makassar",
   ["Reef","Left","Advanced"],
   "The wave that opened Indonesia to the world in 1971. Uluwatu is a series of left-hand reef sections — Racetrack, Outside Corner, The Peak, Temples — running below a clifftop temple, accessed through a cave that you enter and exit with the tide. On a big dry-season swell it is one of the great waves anywhere.",
   "Reef break","Sharp coral reef","Long, fast, barrelling lefts across several sections","Advanced",
   "SW Indian Ocean groundswell","SE trade winds — offshore in the dry season","Mid to high; the cave exit needs water",
   "April–October","27–29°C — boardshorts","Crowded, but the reef is long",
   ["Very sharp shallow coral","The cave entry closes out at low tide","Strong currents between sections","Reef cuts infect fast in the tropics"],
   "Time your exit with the tide — people get stuck outside the cave every season. Antiseptic for reef cuts is not optional.",
   ["DPS"],"About 60 min south from Denpasar",60,
   "Visa on arrival for most nationalities in Indonesia"),

 s("canggu","Canggu (Batu Bolong & Echo)","Bali","Indonesia","ID",-8.6580,115.1300,"Asia/Makassar",
   ["Beach break","Reef","All levels"],
   "Bali's most developed surf town: Batu Bolong is a soft, mellow reef-and-sand wave that suits longboards and learners, Echo Beach next door is a punchier reef, and the whole strip is cafés, scooters and sunset crowds. Consistent, warm and endlessly social.",
   "Reef and beach break","Sand over reef","Mellow rolling lefts and rights at Batu Bolong; punchier at Echo","Beginner to intermediate",
   "SW swell","E–SE offshore in the dry season","Mid to high tide",
   "April–October","27–29°C","Very crowded — one of the busiest lineups in Asia",
   ["Crowds and collisions","Rocks and reef at low tide","Scooter traffic on land","Water quality in the wet season"],
   "Dawn patrol is the only uncrowded window. By 8am Batu Bolong has a hundred people in the water.",
   ["DPS"],"About 45 min north-west from Denpasar",45,
   "Visa on arrival for most nationalities in Indonesia"),

 s("kuta","Kuta Beach","Bali","Indonesia","ID",-8.7180,115.1690,"Asia/Makassar",
   ["Beach break","Beginner","Warm water"],
   "The sandy beach break where most people in Asia catch their first wave. Kuta is a long, forgiving stretch of sand a few minutes from Bali's airport, with soft waves, warm water, board rental every fifty metres and a sunset that draws the whole island.",
   "Beach break","Sand","Soft, slow, forgiving peaks","Beginner",
   "SW swell","E offshore in the dry season","Mid tide",
   "April–October","27–29°C","Extremely busy with lessons",
   ["Crowds of beginners","Rip currents","Beach vendors and theft","Water quality after rain"],
   "Ten minutes from the airport, which makes it the ideal first or last session of a Bali trip.",
   ["DPS"],"10 min from Denpasar airport",10,
   "Visa on arrival for most nationalities in Indonesia"),

 s("bondi","Bondi Beach","Sydney, NSW","Australia","AU",-33.8910,151.2770,"Australia/Sydney",
   ["Beach break","City","All levels"],
   "The most famous city beach in the world. A one-kilometre arc of sand in eastern Sydney with a punchy south-end bank (the Backpackers' Express rip runs beside it), a gentler north end, and a permanent cast of swimmers, lifeguards and locals. Not the best wave in Sydney, but the most alive.",
   "Beach break","Sand","Short, punchy peaks; better at the south end","All levels",
   "S–SE swell","W offshore","Mid to low tide",
   "March–September","17–23°C — spring suit to 3/2","Very busy; surfing is restricted to the flagged-free zones",
   ["Strong rips, especially at the south end","Swimming zones limit where you can surf","Summer crowds"],
   "Bondi is often onshore junk while Maroubra or the northern beaches are clean — check before committing.",
   ["SYD"],"About 30 min from Sydney airport",30,
   "Australia requires an ETA or visa for almost all visitors"),

 s("snapper-rocks","Snapper Rocks & Superbank","Gold Coast, QLD","Australia","AU",-28.1620,153.5480,"Australia/Brisbane",
   ["Point break","Superbank","Expert"],
   "The longest sand-bottomed right in the world, created by accident. A river-dredging project pumped sand around the point in the 1990s and joined Snapper, Rainbow Bay, Greenmount and Kirra into a single bank that on the right swell can carry a wave nearly two kilometres.",
   "Sand-bottom point break","Sand over rock","Very long, fast, hollow right","Advanced — because of the crowd as much as the wave",
   "E–SE cyclone swell","W–SW offshore","Mid tide",
   "January–April (cyclone season)","20–26°C","Among the most crowded lineups on earth",
   ["Extreme crowd — hundreds out on a good day","Rocks at the Snapper takeoff","Strong sweep down the point"],
   "The takeoff at Snapper Rocks is a queue. If you want waves rather than a fight, sit down the line at Greenmount.",
   ["OOL"],"10 min from Gold Coast airport",10,
   "Australia requires an ETA or visa for almost all visitors"),

 s("bells-beach","Bells Beach","Victoria","Australia","AU",-38.3720,144.2810,"Australia/Melbourne",
   ["Point break","Contest","Advanced"],
   "Home of the world's longest-running surf contest, held every Easter since 1962, and the trophy every professional wants to ring. Bells is a big, cold, powerful right-hand point in a natural amphitheatre of cliffs on the Great Ocean Road — a wave that rewards long, drawn-out turns.",
   "Point/reef break","Rock reef","Long, powerful, drawn-out right","Advanced",
   "SW Southern Ocean groundswell","N–NW offshore","Mid to high tide",
   "March–October","13–18°C — 4/3 with boots in winter","Busy in season; the Bowl gets the crowd",
   ["Cold water","Powerful Southern Ocean swell","Rocks","Great whites are present in Victorian waters"],
   "Winkipop next door is faster and often better than Bells itself — do not walk past it.",
   ["AVV","MEL"],"About 35 min from Avalon; roughly 90 min from Melbourne",35,
   "Australia requires an ETA or visa for almost all visitors"),

 s("byron-bay","Byron Bay (The Pass)","NSW","Australia","AU",-28.6360,153.6350,"Australia/Sydney",
   ["Point break","Longboard","All levels"],
   "Australia's easternmost point, and a long, sand-bottomed right-hand point that is one of the great longboard waves in the country. The Pass runs off Cape Byron in slow, tapering walls under a lighthouse, with dolphins in the lineup most mornings and whales passing through in winter.",
   "Sand-bottom point break","Sand over rock","Long, mellow, tapering right","Beginner to intermediate",
   "E–NE swell","SW offshore","Mid to high tide",
   "February–June","19–26°C","Extremely crowded — it is a famous, easy wave",
   ["Heavy crowd","Sharks have been an issue in the region","Strong sweep around the point","Parking is a battle"],
   "Wategos and Little Wategos further round the cape take the same swell with a fraction of the people.",
   ["BNK"],"About 30 min from Ballina Byron Gateway",30,
   "Australia requires an ETA or visa for almost all visitors"),

 s("margaret-river","Margaret River (Main Break)","Western Australia","Australia","AU",-33.9700,114.9930,"Australia/Perth",
   ["Reef","Big wave","Expert"],
   "A big, thick, cold-water reef break that handles serious Indian Ocean swell and hosts a championship tour event. The wider region — from Yallingup to Gracetown — has dozens of reefs, world-class wineries and some of the clearest water in Australia.",
   "Reef break","Granite and limestone reef","Thick, powerful right and left off a deep reef","Advanced to expert",
   "SW Indian Ocean groundswell","E–SE offshore","All tides",
   "March–October","16–22°C — 3/2 to 4/3","Moderate; the region spreads people out",
   ["Powerful swell that jumps in size fast","Great white sharks — this coast has a genuine record","Rocky entries","Remote sections with no help nearby"],
   "The swell here can double between checks. Judge it from the car park over a full set cycle, not a single wave.",
   ["BQB","PER"],"About 45 min from Busselton; roughly 3h from Perth",45,
   "Australia requires an ETA or visa for almost all visitors"),

 s("piha","Piha","Auckland","New Zealand","NZ",-36.9540,174.4680,"Pacific/Auckland",
   ["Beach break","Black sand","Intermediate"],
   "Black volcanic sand, Lion Rock in the middle of the bay, and heavy Tasman Sea beach break forty minutes from central Auckland. Piha is beautiful and genuinely dangerous — it is New Zealand's most rescue-heavy beach and the subject of a long-running documentary series about its lifeguards.",
   "Beach break","Black volcanic sand","Powerful, rippy, shifting peaks","Intermediate to advanced",
   "W–SW Tasman swell","E offshore","Mid to low tide",
   "March–September","15–20°C — 3/2 to 4/3","Busy in summer, empty in winter",
   ["Notorious rip currents — swim between the flags","Powerful shorebreak","Black sand gets scorching hot","Remote west-coast road"],
   "The rips here are the strongest in New Zealand. If you are unsure, surf beside the patrolled flags.",
   ["AKL"],"About 45 min west from Auckland",45,
   "NZ requires an NZeTA for visa-waiver visitors"),

 s("raglan","Raglan (Manu Bay)","Waikato","New Zealand","NZ",-37.8250,174.8010,"Pacific/Auckland",
   ["Point break","Left","Advanced"],
   "One of the longest left-hand points on the planet, made famous by 'The Endless Summer'. Manu Bay, Whale Bay and Indicators run down a boulder coastline west of Raglan and on a big clean SW swell they link into a ride that can last well over a minute.",
   "Point break","Boulder and rock reef","Very long, peeling, walling left","Intermediate to advanced",
   "SW Tasman groundswell","E–SE offshore","Mid tide",
   "April–September","14–20°C — 3/2 to 4/3","Busy but the point is long",
   ["Rocky entry and exit","Strong current down the point","Cold water in winter","Sharp boulders"],
   "Walk further down to Whale Bay if Manu Bay is stacked; it is the same swell with fewer people.",
   ["HLZ","AKL"],"About 45 min from Hamilton; roughly 2h from Auckland",45,
   "NZ requires an NZeTA for visa-waiver visitors"),

 s("shonan","Shonan (Enoshima)","Kanagawa","Japan","JP",35.3080,139.4830,"Asia/Tokyo",
   ["Beach break","Culture","All levels"],
   "Japanese surf culture's home beach, an hour from central Tokyo. Shonan wraps around Enoshima island with Mount Fuji on the horizon on clear winter days. The waves are usually small and soft — which is why it is packed with everyone from grandmothers on longboards to Olympic-level shortboarders.",
   "Beach break","Sand","Small, soft, mellow peaks","Beginner to intermediate",
   "S–SE swell; typhoon swell is the good stuff","N–NW offshore","Mid tide",
   "September–November (typhoon season)","15–27°C","Extremely crowded on weekends",
   ["Very crowded lineup","Often small and weak","Typhoon swell arrives fast and big","Strict local etiquette"],
   "Weekday mornings are civil; weekends are a scrum. Typhoon season is when Shonan actually gets good.",
   ["HND","NRT"],"About 60 min by train from Tokyo to Enoshima",60,
   "Japan is visa-free for many nationalities"),

 s("chiba","Chiba (Ichinomiya)","Chiba","Japan","JP",35.3720,140.3860,"Asia/Tokyo",
   ["Beach break","Olympic","All levels"],
   "The Pacific-facing coast east of Tokyo, and the host of surfing's Olympic debut at Tsurigasaki Beach in 2021. Chiba picks up far more swell than Shonan, with a long run of beach breaks that turn on hard during typhoon season.",
   "Beach break","Sand","Punchy, consistent peaks","All levels",
   "E–SE swell; typhoon swell in autumn","W offshore","Mid tide",
   "September–November","15–27°C","Busy on weekends with Tokyo crowds",
   ["Typhoon swells can be dangerous","Rips","Crowded weekend lineups"],
   "Ichinomiya is the hub, but the coast runs for 60km — drive until you find an empty bank.",
   ["NRT"],"About 60 min by car from Narita",60,
   "Japan is visa-free for many nationalities"),

 s("arugam-bay","Arugam Bay","Eastern Province","Sri Lanka","LK",6.8400,81.8360,"Asia/Colombo",
   ["Point break","Right","All levels"],
   "A long, sandy right-hand point on Sri Lanka's east coast that is one of the friendliest quality point breaks in the world. Warm water, a long peeling wall, elephants in the lagoons behind the town, and a season that runs exactly opposite the island's west coast.",
   "Point break","Sand over rock","Long, mellow, walling right","Beginner to intermediate",
   "S–SE Indian Ocean swell","W offshore in season","Mid tide",
   "May–September","27–29°C — boardshorts","Busy in season but the point is long",
   ["Rocky sections at low tide","Strong sun","Occasional crocodiles in the nearby lagoons — not the surf","Monsoon closes the season"],
   "Whiskey Point and Peanut Farm up the coast are quieter versions of the same wave.",
   ["CMB"],"About 8h by road across the island from Colombo, or a light-aircraft transfer",480,
   "Sri Lanka requires an ETA for most nationalities"),

 s("weligama","Weligama","Southern Province","Sri Lanka","LK",5.9720,80.4290,"Asia/Colombo",
   ["Beach break","Beginner","Warm water"],
   "A wide bay on the south coast with a sandy bottom and waist-high waves that break for a very long way — which makes it one of the best value learn-to-surf destinations in the world. Mirissa and the reefs at Midigama are ten minutes away when you want more.",
   "Beach break","Sand","Slow, soft, long-running whitewater and small walls","Beginner",
   "S–SW Indian Ocean swell","N–NE offshore in season","Mid to high tide",
   "November–April","27–29°C","Very busy with schools",
   ["Crowds of beginners","Shallow rocks at the eastern end","Strong tropical sun"],
   "When Weligama gets too crowded, Midigama's reefs are a ten-minute tuk-tuk away and far better waves.",
   ["CMB"],"About 2.5h south by expressway from Colombo",150,
   "Sri Lanka requires an ETA for most nationalities"),

 s("cloud-nine","Cloud 9, Siargao","Siargao","Philippines","PH",9.8140,126.1670,"Asia/Manila",
   ["Reef","Barrel","Advanced"],
   "The wave that put the Philippines on the surf map: a thick, hollow right-hand reef barrel breaking over shallow coral, with a wooden boardwalk running out to a viewing tower above the lineup. Siargao itself is a teardrop island of palms, lagoons and dirt roads.",
   "Reef break","Shallow coral reef","Thick, hollow, barrelling right","Advanced",
   "E–NE Pacific swell","SW offshore","Mid to high tide — low is dangerously shallow",
   "August–November","28–30°C — boardshorts","Crowded at the peak; other reefs nearby are quiet",
   ["Very shallow sharp coral","Reef cuts infect quickly","Typhoon risk in season","Limited medical facilities"],
   "Do not surf Cloud 9 at low tide. Rent a scooter and find the dozen other reefs on the island instead.",
   ["IAO"],"15 min from Siargao airport to General Luna",15,
   "Many nationalities get 30 days visa-free in the Philippines"),

 s("tel-aviv","Tel Aviv (Hilton & Dolphinarium)","Tel Aviv","Israel","IL",32.0850,34.7660,"Asia/Jerusalem",
   ["Beach break","City","All levels"],
   "A genuine urban surf scene on the Mediterranean, where the waves are small, short-period and wind-driven — and the lineup is packed anyway. Hilton beach in front of the hotel strip is the main peak; winter storms from the west are what everyone waits for.",
   "Beach break","Sand","Short, sharp, quick wind-swell peaks","All levels",
   "W–SW Mediterranean wind swell","E offshore","Mid tide",
   "November–March","17–29°C — shorty or 3/2 in winter","Crowded, energetic, vocal",
   ["Short-period choppy swell","Very crowded peaks","Long flat spells in summer"],
   "Mediterranean swell dies within hours. When a storm shows on the chart, go the same day — not the next.",
   ["TLV"],"20 min from Ben Gurion airport",20,
   "Check Israel's current entry requirements for your nationality"),

 s("unstad","Unstad","Lofoten","Norway","NO",68.2570,13.5330,"Europe/Oslo",
   ["Arctic","Point break","Advanced"],
   "Surfing above the Arctic Circle. Unstad is a small bay in the Lofoten Islands with a right-hand point and a left, ringed by 700-metre peaks, where you can surf under the midnight sun in summer and the northern lights in winter. The water is barely above freezing and the setting is unmatched.",
   "Point and beach break","Sand and rock","Punchy right-hand point and a shorter left","Advanced — because of the conditions, not the wave",
   "NW–N Norwegian Sea swell","S–SE offshore","Mid tide",
   "September–March for swell; summer for midnight sun","4–12°C — 5/4 or 6/5 with hood, gloves and boots","Small, dedicated crew",
   ["Near-freezing water — hypothermia is the real hazard","Very short winter daylight","Remote — hours from a hospital","Arctic storms"],
   "This is a full 6/5 hooded operation in winter. Warm water in a thermos for after the session is standard here.",
   ["LKN","SVJ"],"About 45 min from Leknes",45,
   "Schengen area — check your entry requirements"),

 s("teahupoo","Teahupo'o","Tahiti","French Polynesia","PF",-17.8480,-149.2670,"Pacific/Tahiti",
   ["Reef","Heaviest wave","Expert"],
   "The heaviest wave in the world. Teahupo'o breaks over a shallow coral shelf that rises from deep water almost vertically, so the wave does not so much break as fall — a thick slab of Pacific Ocean landing on dry reef. Olympic venue, championship tour stop, and utterly unforgiving.",
   "Reef break","Shallow, sharp coral shelf","A thick, square, below-sea-level left barrel","Expert only, with safety support",
   "SW–S Pacific groundswell","E–SE offshore","Mid to high tide",
   "May–September","26–28°C","A very small, very experienced crew",
   ["One of the most dangerous waves on earth","Razor-sharp shallow reef","Serious injuries and deaths have occurred","Remote — the hospital is in Papeete"],
   "Almost everyone who comes here watches from a boat at the channel. That is the correct decision.",
   ["PPT"],"About 90 min by road from Papeete to the end of the road",90,
   "French Polynesia — Schengen-style rules apply for many nationalities"),

 s("tavarua","Cloudbreak, Fiji","Mamanuca Islands","Fiji","FJ",-17.8580,177.1930,"Pacific/Fiji",
   ["Reef","Left","Expert"],
   "A left-hand reef pass a kilometre out to sea off Tavarua island, breaking over shallow coral in the middle of the Pacific. Cloudbreak is long, fast and genuinely world-class at every size, from playful head-high to the 20-foot day that produced some of the most famous images in surfing.",
   "Reef pass","Shallow coral reef","Long, fast, barrelling left","Advanced to expert",
   "S–SW Pacific groundswell","E–SE trade winds","Mid to high tide",
   "April–October","26–29°C — boardshorts","Limited — access is by boat, which caps numbers",
   ["Shallow razor coral","Boat access only","Strong current through the pass","Remote from medical care"],
   "Restaurants, the right next door, is shorter and lighter. Cloudbreak on a big day is a professional-level wave.",
   ["NAN"],"About 20 min by road from Nadi plus a 45-min boat transfer",65,
   "Many nationalities get 4 months visa-free in Fiji"),

 s("popoyo","Popoyo","Rivas","Nicaragua","NI",11.4670,-86.1200,"America/Managua",
   ["Reef","Offshore wind","Intermediate"],
   "Nicaragua's signature wave, backed by the most reliable offshore wind on earth: Lake Nicaragua generates a thermal breeze that blows offshore on this coast around 300 days a year. Popoyo has a sand-bottom beach break and an outer reef that holds serious size.",
   "Reef and beach break","Sand and rock reef","Punchy peaks inside; big, powerful outer reef","Intermediate to advanced",
   "SW Pacific groundswell","Offshore almost every morning thanks to the lake effect","Mid tide",
   "April–October","27–29°C","Moderate — the coast is still relatively undeveloped",
   ["Rocks at the reef","Strong offshore wind makes paddling back harder","Remote roads","Limited medical facilities"],
   "The offshore wind that makes this coast is also relentless — a slightly bigger board helps with the paddle in.",
   ["MGA"],"About 3h south-west by road from Managua",180,
   "Most nationalities buy a tourist card on arrival in Nicaragua"),
]

def main():
    catalog = {
        "version": 1,
        "updated": datetime.date.today().isoformat(),
        "spots": SPOTS,
    }
    path = "app/src/main/assets/spots.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(catalog, f, ensure_ascii=False, indent=1)
    print(f"wrote {len(SPOTS)} spots -> {path}")

if __name__ == "__main__":
    main()
