/* Glossary: every term and symbol used in the course, searchable.
   `ex` renders a small piece of music so you can see the symbol in context. */

export const GLOSSARY = [
  { g: "The keyboard", items: [
    { t: "Middle C", d: "The C nearest the middle of the piano (C4). Written on a ledger line between the two staves. Home base for reading." },
    { t: "Octave", d: "The distance from one note to the next note with the same name, 12 half steps. C4 → C5 is one octave up." },
    { t: "Half step (semitone)", d: "From one key to the very next key, black or white. The smallest step on the piano." },
    { t: "Whole step (tone)", d: "Two half steps, e.g. C → D, or E → F♯." },
    { t: "Finger numbers", d: "Thumb = 1, index = 2, middle = 3, ring = 4, pinky = 5 — the same for both hands." },
    { t: "Hand position", d: "One finger resting over each of five neighbouring keys, e.g. C position: C D E F G." },
  ]},
  { g: "Staff & clefs", items: [
    { t: "Staff", d: "Five lines and four spaces. Higher on the staff = higher sound." },
    { t: "Treble clef (G clef)", d: "Curls around the 2nd line to mark G above middle C. Usually for the right hand.", ex: { ts: "4/4", bare: true, rh: "G4w" } },
    { t: "Bass clef (F clef)", d: "Its two dots surround the 4th line, marking F below middle C. Usually for the left hand.", ex: { ts: "4/4", bare: true, lh: "F3w" } },
    { t: "Grand staff", d: "Treble and bass staves joined by a brace — piano music." },
    { t: "Ledger lines", d: "Short extra lines for notes above or below the staff.", ex: { ts: "4/4", bare: true, rh: "A5h C4h" } },
    { t: "Bar line / measure (bar)", d: "Vertical lines divide the music into measures of equal length. A double bar ends the piece." },
  ]},
  { g: "Rhythm", items: [
    { t: "Beat", d: "The steady pulse you tap your foot to." },
    { t: "Whole note", d: "Hollow, no stem — 4 beats.", ex: { ts: "4/4", rh: "C5w" } },
    { t: "Half note", d: "Hollow with a stem — 2 beats.", ex: { ts: "4/4", rh: "C5h C5h" } },
    { t: "Quarter note", d: "Filled with a stem — 1 beat.", ex: { ts: "4/4", rh: "C5q C5 C5 C5" } },
    { t: "Eighth note", d: "Half a beat; two are joined by a beam. Count “1 and”.", ex: { ts: "4/4", rh: "C5e C5 C5 C5 C5 C5 C5 C5" } },
    { t: "Sixteenth note", d: "A quarter of a beat; double beam. Count “1 e and a”.", ex: { ts: "4/4", rh: "C5s C5 C5 C5 C5 C5 C5 C5 C5h" } },
    { t: "Dotted note", d: "A dot adds half the note's value: dotted half = 3 beats, dotted quarter = 1½.", ex: { ts: "4/4", rh: "C5q. C5e C5h" } },
    { t: "Rests", d: "Silences with the same values as notes: whole, half, quarter, eighth rest.", ex: { ts: "4/4", rh: "rh rq re re" } },
    { t: "Time signature", d: "Top number: beats per measure. Bottom number: which note gets one beat (4 = quarter, 8 = eighth). 4/4, 3/4, 6/8…" },
    { t: "Pickup (anacrusis)", d: "Note(s) before the first full measure, like “Hap-py” in Happy Birthday." },
    { t: "Tie", d: "A curved line joining two notes of the same pitch: hold them as one long note." },
    { t: "Triplet", d: "Three notes squeezed into the time of two, marked with a 3." },
    { t: "Syncopation", d: "Accenting off-beats — the bounce of ragtime, jazz and pop." },
  ]},
  { g: "Accidentals & keys", items: [
    { t: "Sharp ♯", d: "Raise a note by a half step.", ex: { ts: "4/4", bare: true, rh: "F#4w" } },
    { t: "Flat ♭", d: "Lower a note by a half step.", ex: { ts: "4/4", bare: true, rh: "Bb4w" } },
    { t: "Natural ♮", d: "Cancel a sharp or flat.", ex: { ts: "4/4", bare: true, rh: "F#4h Fn4h" } },
    { t: "Key signature", d: "Sharps or flats at the start of each staff, applying to every note of that letter all piece long.", ex: { ts: "4/4", key: "D", rh: "D5w" } },
    { t: "Scale", d: "A ladder of notes from one note to its octave. Major: W W H W W W H." },
    { t: "Relative minor", d: "The minor key sharing a major key's signature, starting on its 6th note (C major ↔ A minor)." },
    { t: "Circle of fifths", d: "All 12 keys arranged by fifths; each step clockwise adds a sharp, counter-clockwise a flat." },
    { t: "Enharmonic", d: "Two names for one key: C♯ = D♭." },
    { t: "Chromatic", d: "Moving by half steps, using every key." },
  ]},
  { g: "Harmony", items: [
    { t: "Interval", d: "The distance between two notes, counted in letter names including both ends: C–E is a 3rd." },
    { t: "Chord / triad", d: "Three or more notes together. A triad is root + 3rd + 5th.", ex: { ts: "4/4", rh: "C4+E4+G4w" } },
    { t: "Major / minor chord", d: "Major (4+3 half steps) sounds bright; minor (3+4) sounds darker." },
    { t: "Inversion", d: "A chord with a note other than the root on the bottom.", ex: { ts: "4/4", rh: "C4+E4+G4h E4+G4+C5h" } },
    { t: "Seventh chord", d: "A triad plus the 7th: maj7, 7 (dominant), m7, m7♭5, dim7." },
    { t: "Roman numerals", d: "Chords named by scale degree: I, ii, iii, IV, V, vi, vii° in major." },
    { t: "Progression", d: "A sequence of chords, e.g. I–V–vi–IV or ii–V–I." },
    { t: "Cadence", d: "A chord ending to a phrase, like V → I (perfect/authentic cadence)." },
    { t: "Voice leading", d: "Moving each note of one chord to the nearest note of the next." },
    { t: "Lead sheet", d: "Melody plus chord symbols; the pianist creates the accompaniment." },
    { t: "Arpeggio / broken chord", d: "Chord notes played one after another.", ex: { ts: "4/4", rh: "C4e E4 G4 C5 G4 E4 C4q" } },
    { t: "Alberti bass", d: "Broken-chord pattern low–high–middle–high, typical of Mozart." },
  ]},
  { g: "Dynamics", items: [
    { t: "pp · p · mp", d: "Pianissimo (very soft), piano (soft), mezzo-piano (medium soft)." },
    { t: "mf · f · ff", d: "Mezzo-forte (medium loud), forte (loud), fortissimo (very loud).", ex: { ts: "4/4", rh: "!p C5h !f C5h" } },
    { t: "Crescendo / diminuendo", d: "Gradually louder (cresc., <) / gradually softer (dim., >)." },
    { t: "Accent >", d: "Emphasize this note." },
  ]},
  { g: "Articulation & pedal", items: [
    { t: "Legato", d: "Smooth and connected — a slur (curved line) over notes." },
    { t: "Staccato", d: "A dot above/below the note: short and detached.", ex: { ts: "4/4", rh: "C5q' D5' E5' F5'" } },
    { t: "Tenuto", d: "A line over the note: hold it for its full value, slightly leaned on." },
    { t: "Fermata", d: "Hold the note longer than written." },
    { t: "Sustain pedal (Ped. / *)", d: "Right pedal; keeps notes ringing. Change it with each new harmony.", ex: { ts: "4/4", rh: "C4+E4+G4w | C4+F4+A4w", lh: "!ped C3w | !ped F2w !*" } },
    { t: "Una corda", d: "Left (soft) pedal; a softer, veiled tone." },
  ]},
  { g: "Tempo & form", items: [
    { t: "BPM", d: "Beats per minute — the metronome speed." },
    { t: "Largo · Adagio · Andante", d: "Very slow · slow · walking pace." },
    { t: "Moderato · Allegro · Presto", d: "Moderate · fast and lively · very fast." },
    { t: "Ritardando (rit.) / accelerando", d: "Gradually slower / gradually faster." },
    { t: "A tempo", d: "Return to the original speed." },
    { t: "Rubato", d: "Flexible tempo for expression — typical of Chopin." },
    { t: "Repeat signs", d: "Double bar with two dots: play the section again. D.C. = from the beginning; Fine = end." },
    { t: "Phrase", d: "A musical sentence, often 4 or 8 bars; breathe between phrases." },
  ]},
  { g: "Technique & practice", items: [
    { t: "Thumb under / cross over", d: "How the hand moves past five notes in scales and arpeggios." },
    { t: "Voicing", d: "Making one note of a chord (usually the melody) louder than the others." },
    { t: "Hands separately (HS) / together (HT)", d: "Learn each hand alone before combining." },
    { t: "Chunking", d: "Practicing a small section until secure, then linking it to its neighbours." },
    { t: "Sight-reading", d: "Playing music you've never seen before, keeping the pulse going." },
  ]},
];
